export const gisLayerRoadmap = [
  {
    id: 'admin-boundaries',
    label: 'Administrative boundaries',
    phase: 'Phase 3',
    description: 'Base region boundaries for state and district planning views.',
  },
  {
    id: 'hazard-overlays',
    label: 'Hazard overlays',
    phase: 'Phase 3',
    description: 'Future flood, landslide, erosion, and cloudburst spatial layers.',
  },
  {
    id: 'red-zones',
    label: 'Derived Red Zones',
    phase: 'Phase 4',
    description: 'Unsafe habitation zones generated by deterministic risk analysis.',
  },
] as const;
