import { criticalInfrastructureFixture } from '@/server/db/fixtures/disaster-data';
import { getHabitationById, getHabitations } from '@/server/repositories/habitations';
import { getRedZones } from '@/server/repositories/red-zones';
import { getRelocationSites } from '@/server/repositories/relocation-sites';
import { getRegionalCapacityRollup } from '@/server/capacity/capacity-service';
import {
  findRelocationCandidates,
  type HabitationRelocationPlan,
} from '@/server/relocation/matching-engine';
import { calculateHabitationRisk } from '@/server/risk/risk-engine';
import type {
  Habitation,
  HazardType,
  RelocationSite,
} from '@/types/domain';
import type {
  ExecutiveAuthoritySummaryReport,
  GisCoordinateAppendix,
  GisFeatureSummary,
  HabitationVulnerabilityDossierReport,
  RelocationJustificationReport,
  ReportMetadata,
  ReportType,
  ScenarioImpactReport,
} from './report-types';

const MODEL_VERSION = 'SIH26191-ENGINE-V2.0';
const DEFAULT_JURISDICTION = 'State Disaster Management Authority (SDMA)';
const PROVENANCE_DISCLAIMER =
  'DEMO / SEEDED DATA — NOT AN OFFICIAL GOVERNMENT RECORD. Generated by SIH26191 Deterministic Decision-Support Engine for operational planning and evaluation purposes.';

function createReportMetadata(
  reportType: ReportType,
  title: string,
  entityId: string,
): ReportMetadata {
  const dateStr = new Date().toISOString();
  const slugId = `${reportType.toUpperCase()}-${entityId}-${Date.now().toString(36).toUpperCase()}`;

  return {
    reportId: `RPT-${slugId}`,
    title,
    reportType,
    generatedAt: dateStr,
    authorityJurisdiction: DEFAULT_JURISDICTION,
    modelVersion: MODEL_VERSION,
    provenance: 'DEMO DATA',
    disclaimer: PROVENANCE_DISCLAIMER,
  };
}

/**
 * Builds GIS Coordinate Appendix (WGS84 / EPSG:4326) for a target habitation and candidate sites.
 */
export function buildGisAppendix(
  habitation: Habitation,
  candidateSites: RelocationSite[] = [],
): GisCoordinateAppendix {
  const candidateSiteFeatures: GisFeatureSummary[] = candidateSites.map((s) => ({
    featureId: s.id,
    featureType: 'relocation_site',
    name: s.name,
    district: s.district,
    state: s.state,
    coordinates: s.coordinates,
    crs: 'EPSG:4326 (WGS84)',
    notes: `${s.areaHectares} ha · ${s.carryingCapacity} cap`,
  }));

  const infrastructureFeatures: GisFeatureSummary[] = criticalInfrastructureFixture
    .filter((inf) => inf.district.toLowerCase() === habitation.district.toLowerCase())
    .map((inf) => ({
      featureId: inf.id,
      featureType: 'infrastructure',
      name: inf.name,
      district: inf.district,
      state: inf.state,
      coordinates: inf.coordinates,
      crs: 'EPSG:4326 (WGS84)',
      notes: `Critical Infrastructure (${inf.kind})`,
    }));

  return {
    crs: 'EPSG:4326 (WGS84)',
    subjectCoordinates: habitation.coordinates,
    redZoneFeatures: habitation.redZoneId
      ? [
          {
            featureId: habitation.redZoneId,
            featureType: 'red_zone',
            name: `Red Zone Envelope (${habitation.redZoneId})`,
            district: habitation.district,
            state: habitation.state,
            coordinates: habitation.coordinates,
            crs: 'EPSG:4326 (WGS84)',
            notes: `High-hazard containment envelope for ${habitation.primaryHazard}`,
          },
        ]
      : [],
    candidateSiteFeatures,
    infrastructureFeatures,
  };
}

/**
 * Compiles a comprehensive Habitation Vulnerability Dossier.
 */
export async function buildHabitationVulnerabilityDossier(
  habitationId: string,
): Promise<HabitationVulnerabilityDossierReport | null> {
  const habitation = await getHabitationById(habitationId);
  if (!habitation) return null;

  const [allRedZones, allSites] = await Promise.all([
    getRedZones({ district: habitation.district }),
    getRelocationSites({ district: habitation.district }),
  ]);

  const riskAssessment = calculateHabitationRisk(habitation);
  const redZone = allRedZones.find((rz) => rz.id === habitation.redZoneId);

  const metadata = createReportMetadata(
    'vulnerability_dossier',
    `Multi-Hazard Vulnerability Dossier: ${habitation.name}`,
    habitation.id,
  );

  const gisAppendix = buildGisAppendix(habitation, allSites);

  return {
    metadata,
    habitation,
    riskAssessment,
    demographics: habitation.demographics,
    infrastructure: habitation.infrastructure,
    disasterHistory: habitation.history,
    redZoneRelationship: {
      isContained: !!habitation.redZoneId,
      redZoneId: habitation.redZoneId,
      redZoneName: redZone?.name,
      hazardSeverity: redZone?.severity,
    },
    gisAppendix,
  };
}

/**
 * Compiles an official Relocation Justification Report for statutory review.
 */
export async function buildRelocationJustificationReport(
  habitationId: string,
): Promise<RelocationJustificationReport | null> {
  const habitation = await getHabitationById(habitationId);
  if (!habitation) return null;

  const allSites = await getRelocationSites();
  const plan: HabitationRelocationPlan = findRelocationCandidates(habitation, allSites);

  const metadata = createReportMetadata(
    'relocation_justification',
    `Statutory Relocation Justification Report: ${habitation.name}`,
    habitation.id,
  );

  const matchedSites = [
    ...(plan.recommendedSite ? [plan.recommendedSite.site] : []),
    ...plan.alternativeSites.map((a) => a.site),
  ];
  const gisAppendix = buildGisAppendix(habitation, matchedSites);

  const statutoryMandate = {
    mandateHeadline: plan.decisionExplanation.headline,
    disasterActReference:
      habitation.priority === 'CRITICAL'
        ? 'Disaster Management Act 2005 (Section 30/34) - Proactive Resettlement Protocol'
        : 'State Disaster Mitigation Plan (SDMP) - Phased Relocation Guidelines',
    urgencyWindow: plan.riskAssessment.urgencyWindow,
    priorityLevel: habitation.priority,
  };

  return {
    metadata,
    habitation,
    riskAssessment: plan.riskAssessment,
    statutoryMandate,
    recommendedSite: plan.recommendedSite,
    alternativeSites: plan.alternativeSites,
    unabsorbedPopulation: plan.unabsorbedPopulation,
    overallFeasibility: plan.overallFeasibility,
    decisionExplanation: plan.decisionExplanation,
    gisAppendix,
  };
}

/**
 * Compiles a command-level Executive Authority Summary across habitations.
 */
export async function buildExecutiveAuthoritySummary(
  districtFilter?: string,
): Promise<ExecutiveAuthoritySummaryReport> {
  const [habitations, capacityRollup, allSites] = await Promise.all([
    getHabitations({ district: districtFilter }),
    getRegionalCapacityRollup({ district: districtFilter }),
    getRelocationSites({ district: districtFilter }),
  ]);

  const totalAssessedHabitations = habitations.length;
  const populationAtRisk = habitations.reduce((sum, h) => sum + h.population, 0);

  // Calculate plans for top priority summary
  const plans = habitations.map((h) => findRelocationCandidates(h, allSites));

  const priorityBreakdown = {
    immediate: plans.filter((p) => p.habitation.priority === 'CRITICAL').length,
    shortTerm: plans.filter((p) => p.habitation.priority === 'HIGH').length,
    mediumTerm: plans.filter((p) => p.habitation.priority === 'MEDIUM').length,
    monitor: plans.filter((p) => p.habitation.priority === 'LOW').length,
  };

  // Hazard Distribution
  const hazardDistribution: Record<HazardType, number> = {
    landslide: 0,
    flood: 0,
    cloudburst: 0,
    coastal_erosion: 0,
    multi_hazard: 0,
  };

  habitations.forEach((h) => {
    if (h.primaryHazard in hazardDistribution) {
      hazardDistribution[h.primaryHazard]++;
    }
  });

  // District statistics
  const districtMap = new Map<
    string,
    { district: string; state: string; habitationsCount: number; populationAtRisk: number; criticalCount: number }
  >();

  habitations.forEach((h) => {
    const existing = districtMap.get(h.district) ?? {
      district: h.district,
      state: h.state,
      habitationsCount: 0,
      populationAtRisk: 0,
      criticalCount: 0,
    };

    existing.habitationsCount++;
    existing.populationAtRisk += h.population;
    if (h.priority === 'CRITICAL') existing.criticalCount++;
    districtMap.set(h.district, existing);
  });

  const districtsRepresented = Array.from(districtMap.values()).sort(
    (a, b) => b.criticalCount - a.criticalCount,
  );

  // Top Priority Habitations (Sorted by risk score)
  const topPriorityHabitations = plans
    .sort((a, b) => b.riskAssessment.compositeScore - a.riskAssessment.compositeScore)
    .slice(0, 10)
    .map((p) => ({
      id: p.habitation.id,
      name: p.habitation.name,
      district: p.habitation.district,
      population: p.habitation.population,
      hazard: p.habitation.primaryHazard,
      riskScore: p.riskAssessment.compositeScore,
      priority: p.habitation.priority,
      timeline: p.habitation.timeline,
      recommendedSiteName: p.recommendedSite?.site.name ?? null,
    }));

  const netShortfall = plans.reduce((sum, p) => sum + p.unabsorbedPopulation, 0);

  const keyOperationalRecommendations = [
    `Prioritize immediate resettlement allocation for ${priorityBreakdown.immediate} Critical settlements (${populationAtRisk.toLocaleString('en-IN')} total population evaluated).`,
    `Ensure developable land clearances for candidate sectors currently showing limiting bottlenecks in emergency shelter and water networks.`,
    `Commission GIS boundary demarcation along Red Zone perimeters to restrict unauthorized building reconstruction in identified runout envelopes.`,
    `Execute inter-agency infrastructure synchronization to upgrade healthcare and road access ratings across high-absorption resettlement sectors.`,
  ];

  const metadata = createReportMetadata(
    'executive_summary',
    `Executive Multi-Hazard & Relocation Summary Report${districtFilter ? ` (${districtFilter})` : ''}`,
    districtFilter ?? 'ALL-DISTRICTS',
  );

  return {
    metadata,
    scope: {
      district: districtFilter,
      totalAssessedHabitations,
      populationAtRisk,
      totalCandidateSites: capacityRollup.totalSites,
      totalAvailableHeadroom: capacityRollup.totalAvailableHeadroom,
      netShortfall,
    },
    priorityBreakdown,
    hazardDistribution,
    districtsRepresented,
    topPriorityHabitations,
    keyOperationalRecommendations,
  };
}

/**
 * Builds a comprehensive scenario impact report comparing baseline vs simulated environmental stress.
 */
export async function buildScenarioImpactReport(
  scenarioId: string = 'monsoon_rainfall_20',
  districtFilter?: string,
): Promise<ScenarioImpactReport> {
  const { runScenarioSimulation } = await import('@/server/scenarios/scenario-service');
  const impactSummary = await runScenarioSimulation(scenarioId, undefined, districtFilter);

  const metadata = createReportMetadata(
    'scenario_impact',
    `Multi-Hazard Scenario Simulation Impact Report: ${impactSummary.scenario.name}`,
    districtFilter ?? 'ALL-DISTRICTS',
  );

  return {
    metadata,
    impactSummary,
  };
}
